# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x06server\"c\n\nPlayerData\x12\x13\n\x0bplayer_uuid\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08username\x18\x03 \x01(\t\x12\r\n\x05\x63olor\x18\x04 \x01(\t\x12\x0c\n\x04slot\x18\x05 \x01(\x05\"\x81\x01\n\tGameState\x12$\n\x07players\x18\x01 \x03(\x0b\x32\x13.server.PlayerState\x12(\n\tasteroids\x18\x02 \x03(\x0b\x32\x15.server.AsteroidState\x12$\n\x07\x62ullets\x18\x03 \x03(\x0b\x32\x13.server.BulletState\"`\n\x0bPlayerState\x12\x13\n\x0bplayer_uuid\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0c\n\x04posX\x18\x03 \x01(\x05\x12\x0c\n\x04posY\x18\x04 \x01(\x05\x12\r\n\x05\x61ngle\x18\x05 \x01(\x05\"q\n\nPlayerShot\x12\x13\n\x0bplayer_uuid\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\r\n\x05speed\x18\x03 \x01(\x05\x12\x10\n\x08rotation\x18\x04 \x01(\x05\x12\x0c\n\x04posX\x18\x05 \x01(\x05\x12\x0c\n\x04posY\x18\x06 \x01(\x05\":\n\rAsteroidState\x12\x0c\n\x04posX\x18\x01 \x01(\x05\x12\x0c\n\x04posY\x18\x02 \x01(\x05\x12\r\n\x05\x61ngle\x18\x03 \x01(\x05\"8\n\x0b\x42ulletState\x12\x0c\n\x04posX\x18\x01 \x01(\x05\x12\x0c\n\x04posY\x18\x02 \x01(\x05\x12\r\n\x05\x61ngle\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2\xaa\x01\n\x0bGameService\x12\x34\n\x08JoinGame\x12\x12.server.PlayerData\x1a\x12.server.PlayerData0\x01\x12\x33\n\tSendState\x12\x13.server.PlayerState\x1a\x11.server.GameState\x12\x30\n\x0cGetGameState\x12\r.server.Empty\x1a\x11.server.GameStateB\x0fZ\rTrashed/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rTrashed/proto'
  _globals['_PLAYERDATA']._serialized_start=25
  _globals['_PLAYERDATA']._serialized_end=124
  _globals['_GAMESTATE']._serialized_start=127
  _globals['_GAMESTATE']._serialized_end=256
  _globals['_PLAYERSTATE']._serialized_start=258
  _globals['_PLAYERSTATE']._serialized_end=354
  _globals['_PLAYERSHOT']._serialized_start=356
  _globals['_PLAYERSHOT']._serialized_end=469
  _globals['_ASTEROIDSTATE']._serialized_start=471
  _globals['_ASTEROIDSTATE']._serialized_end=529
  _globals['_BULLETSTATE']._serialized_start=531
  _globals['_BULLETSTATE']._serialized_end=587
  _globals['_EMPTY']._serialized_start=589
  _globals['_EMPTY']._serialized_end=596
  _globals['_GAMESERVICE']._serialized_start=599
  _globals['_GAMESERVICE']._serialized_end=769
# @@protoc_insertion_point(module_scope)
