// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerUuid    string                 `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` //For sync
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Slot          int32                  `protobuf:"varint,5,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerData) Reset() {
	*x = PlayerData{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerData) ProtoMessage() {}

func (x *PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerData.ProtoReflect.Descriptor instead.
func (*PlayerData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerData) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *PlayerData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlayerData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerData) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *PlayerData) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerState         `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Asteroids     []*AsteroidState       `protobuf:"bytes,2,rep,name=asteroids,proto3" json:"asteroids,omitempty"`
	Bullets       []*BulletState         `protobuf:"bytes,3,rep,name=bullets,proto3" json:"bullets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *GameState) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetAsteroids() []*AsteroidState {
	if x != nil {
		return x.Asteroids
	}
	return nil
}

func (x *GameState) GetBullets() []*BulletState {
	if x != nil {
		return x.Bullets
	}
	return nil
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerUuid    string                 `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` //For sync
	PosX          int32                  `protobuf:"varint,3,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY          int32                  `protobuf:"varint,4,opt,name=posY,proto3" json:"posY,omitempty"`
	Angle         int32                  `protobuf:"varint,5,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerState) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *PlayerState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlayerState) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlayerState) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *PlayerState) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type PlayerShot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerUuid    string                 `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Speed         int32                  `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Rotation      int32                  `protobuf:"varint,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	PosX          int32                  `protobuf:"varint,5,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY          int32                  `protobuf:"varint,6,opt,name=posY,proto3" json:"posY,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerShot) Reset() {
	*x = PlayerShot{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerShot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerShot) ProtoMessage() {}

func (x *PlayerShot) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerShot.ProtoReflect.Descriptor instead.
func (*PlayerShot) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerShot) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *PlayerShot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlayerShot) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PlayerShot) GetRotation() int32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *PlayerShot) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlayerShot) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

type AsteroidState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosX          int32                  `protobuf:"varint,1,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY          int32                  `protobuf:"varint,2,opt,name=posY,proto3" json:"posY,omitempty"`
	Angle         int32                  `protobuf:"varint,3,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsteroidState) Reset() {
	*x = AsteroidState{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsteroidState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsteroidState) ProtoMessage() {}

func (x *AsteroidState) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsteroidState.ProtoReflect.Descriptor instead.
func (*AsteroidState) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *AsteroidState) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *AsteroidState) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *AsteroidState) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type BulletState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosX          int32                  `protobuf:"varint,1,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY          int32                  `protobuf:"varint,2,opt,name=posY,proto3" json:"posY,omitempty"`
	Angle         int32                  `protobuf:"varint,3,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletState) Reset() {
	*x = BulletState{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletState) ProtoMessage() {}

func (x *BulletState) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletState.ProtoReflect.Descriptor instead.
func (*BulletState) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *BulletState) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *BulletState) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *BulletState) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x06server\"\x91\x01\n" +
	"\n" +
	"PlayerData\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x12\n" +
	"\x04slot\x18\x05 \x01(\x05R\x04slot\"\x9e\x01\n" +
	"\tGameState\x12-\n" +
	"\aplayers\x18\x01 \x03(\v2\x13.server.PlayerStateR\aplayers\x123\n" +
	"\tasteroids\x18\x02 \x03(\v2\x15.server.AsteroidStateR\tasteroids\x12-\n" +
	"\abullets\x18\x03 \x03(\v2\x13.server.BulletStateR\abullets\"\x8a\x01\n" +
	"\vPlayerState\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04posX\x18\x03 \x01(\x05R\x04posX\x12\x12\n" +
	"\x04posY\x18\x04 \x01(\x05R\x04posY\x12\x14\n" +
	"\x05angle\x18\x05 \x01(\x05R\x05angle\"\xa5\x01\n" +
	"\n" +
	"PlayerShot\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x05R\x05speed\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x05R\brotation\x12\x12\n" +
	"\x04posX\x18\x05 \x01(\x05R\x04posX\x12\x12\n" +
	"\x04posY\x18\x06 \x01(\x05R\x04posY\"M\n" +
	"\rAsteroidState\x12\x12\n" +
	"\x04posX\x18\x01 \x01(\x05R\x04posX\x12\x12\n" +
	"\x04posY\x18\x02 \x01(\x05R\x04posY\x12\x14\n" +
	"\x05angle\x18\x03 \x01(\x05R\x05angle\"K\n" +
	"\vBulletState\x12\x12\n" +
	"\x04posX\x18\x01 \x01(\x05R\x04posX\x12\x12\n" +
	"\x04posY\x18\x02 \x01(\x05R\x04posY\x12\x14\n" +
	"\x05angle\x18\x03 \x01(\x05R\x05angle\"\a\n" +
	"\x05Empty2\xaa\x01\n" +
	"\vGameService\x124\n" +
	"\bJoinGame\x12\x12.server.PlayerData\x1a\x12.server.PlayerData0\x01\x123\n" +
	"\tSendState\x12\x13.server.PlayerState\x1a\x11.server.GameState\x120\n" +
	"\fGetGameState\x12\r.server.Empty\x1a\x11.server.GameStateB\x0fZ\rTrashed/protob\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_proto_goTypes = []any{
	(*PlayerData)(nil),    // 0: server.PlayerData
	(*GameState)(nil),     // 1: server.GameState
	(*PlayerState)(nil),   // 2: server.PlayerState
	(*PlayerShot)(nil),    // 3: server.PlayerShot
	(*AsteroidState)(nil), // 4: server.AsteroidState
	(*BulletState)(nil),   // 5: server.BulletState
	(*Empty)(nil),         // 6: server.Empty
}
var file_server_proto_depIdxs = []int32{
	2, // 0: server.GameState.players:type_name -> server.PlayerState
	4, // 1: server.GameState.asteroids:type_name -> server.AsteroidState
	5, // 2: server.GameState.bullets:type_name -> server.BulletState
	0, // 3: server.GameService.JoinGame:input_type -> server.PlayerData
	2, // 4: server.GameService.SendState:input_type -> server.PlayerState
	6, // 5: server.GameService.GetGameState:input_type -> server.Empty
	0, // 6: server.GameService.JoinGame:output_type -> server.PlayerData
	1, // 7: server.GameService.SendState:output_type -> server.GameState
	1, // 8: server.GameService.GetGameState:output_type -> server.GameState
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
